site_name: Pinta Pals
nav:
  - Home: index.md
  - First Steps:
    - 'Getting Started': start.md
  - Tutorial: tutorial.md
  - Images:
    - 'Add & Remove Images': images.md
    - 'Select & Edit Images': edit_images.md
  - Layers:
    - 'Add & Remove Layers': layers.md
    - 'General Overview': overview.md
    - 'Basic Concepts': concept.md
  - Quick Start: 
    - 'Setting Up Project': setup.md
    - 'Tutorial': tutorial.md
  - Image Layers:
    - 'Creating Layers': layers.md
    - 'Edit Layers': edit_layers.md
    - 'Remove Layers': remove_layers.md
  - Drawing & Painting:
    - 'About Drawing': pencil.md
    - 'Selection Tool': select.md
    - 'Selecting Pencil and Brush': paintbrush.md
    - 'Add Shapes': shapes.md
    - 'Add Lines & Curves': lines.md
    - 'Removing Items': items.md
    - 'Text Management': text.md
  - Image Transformations:
    - 'Rotate': rotate.md
    - 'Flip': flip.md
    - 'Resize': resize.md
    - 'Noise Reduction': noise.md
    - 'Posterize': posterize.md
  - Colour Level: 
    - 'Auto Level': auto.md
    - 'Manual Level': manual.md
  - Save Project: save.md
  - Print Project: print.md
  - Shortcuts: shortcuts.md
  - Glossary: glossary.md
  - Test: test.md
theme: readthedocs
